### ISSUE TITLE
Implement main velocity-updating function

### ISSUE THREAD

**Issue by mklecha** [karolmie1/PSO_Algorithm_Implementation#17]
In utils.R

2. Add dependence on weigths
3. Add weigths to properties
1. Implement main evaluating function
   * updatePointVelocity <- function(velocity, bestLocalCoordinates, bestGlobalCoordinates)
   * must return list of new velocities

**Comment by karolmie1** [comment]
@mklecha Isn't that what should be done in model update? I mean it is literaly model update. 
Why would it be done in utils?

Utils are just those functions that user should provide himself, parameters to metaheuristicRun -> initialization, startPoints, termination, evaluation. This way user don't have to but can provide them by himself. 

Unless you are dooing this as subissue for model init than it's ok, but otherwise i would close as won't fix.

**Comment by mklecha** [comment]
OK, if thats what Utils is meant to be, I'll just move this function.
Subissue is excatly what i had in mind.

**Comment by mklecha** [comment]
TODO Add test
